import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import FoodProductStyle from '../Components/FoodProductStyle.module.css';
import { useRouter } from 'next/router';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const router = useRouter(); 
  return (
    <>
      <Head>
        <title>Let's Tour</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex justify-center'>
        <div>
        <div style={{
          backgroundColor: '#19A7CE',
          borderRadius: '5px',
          width: '420px'
        }} className="relative modal-box">
          <div>
            <div>
              <h1 className="flex justify-center text-4xl text-white">Sign up here</h1>
              <div className=" mt-6">
                <div>
                  <input type="text" placeholder='Type your name here' className="bg-black border-0 input focus:outline-none w-full" />

                  <input type="email" placeholder='Type your email here' className="bg-black border-0 input my-6 focus:outline-none w-full" required />

                  <select className="select w-full border-0 bg-black">
                    <option disabled selected>Reader</option>
                    <option>Admin</option>
                    <option>Author</option>
                  </select>

                  <input type="file" className="bg-black file-input file-input-error focus:outline-none w-full my-6" />

                  <button className={`block mx-auto mb-4 w-full text-xl hover:text-white normal-case hover:bg-black border-0 btn text-black bg-white`}>Sign up</button>

                </div>
              </div>
            </div>
          </div>

        </div>

        <div className='flex justify-around'>
          <label onClick={()=>router.push('/addPost')} style={{
            backgroundImage: "linear-gradient(45deg ,#FEA1BF, #BFEAF5)",
            backgroundSize: "100%",
            backgroundRepeat: "repeat",
          }} className={`normal-case btn ${FoodProductStyle.moreFoodButton} btn-sm border-0 text-xl text-black mt-2 w-32`}>Add Post
          </label>

          <label onClick={()=>router.push('/readPost')} style={{
            backgroundImage: "linear-gradient(45deg ,green ,white)",
            backgroundSize: "100%",
            backgroundRepeat: "repeat",
          }} className={`normal-case btn ${FoodProductStyle.logOut} btn-sm border-0 text-xl text-black mt-2 w-32`}>Read Posts
          </label>

        </div>
        </div>
      </main>
    </>
  )
}
